#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'tutorial_types'

INT32CONSTANT = 9853

MAPCONSTANT = {
  %q"goodnight" => %q"moon",
  %q"hello" => %q"world",
}

